select id,
    name,
    host,
    default_locale,
    available_locales,
    created_at,
    updated_at,
    {{ lang('description') }} as description,
    logo,
    twitter_handler,
    favicon,
    instagram_handler,
    facebook_handler,
    youtube_handler,
    github_handler,
    official_img_header,
    official_url,
    reference_prefix,
    secondary_hosts,
    available_authorizations,
    header_snippets,
    cta_button_text,
    cta_button_path,
    enable_omnipresent_banner,
    {{ lang('omnipresent_banner_title') }} as omnipresent_banner_title,
    omnipresent_banner_url,
    highlighted_content_banner_enabled,
    {{ lang('highlighted_content_banner_title') }} as highlighted_content_banner_title,
    {{ lang('highlighted_content_banner_short_description') }} as highlighted_content_banner_short_description,
    tos_version,
    badges_enabled,
    send_welcome_notification,
    users_registration_mode,
    time_zone
from {{ source('decidim', 'decidim_organizations') }}
where host = '{{ env_var('DBT_DECIDIM') }}'
