select
    id,
    decidim_component_id,
    decidim_scope_id,
    created_at,
    updated_at,
    proposal_votes_count,
    state,
    answered_at,
    {{ lang('answer') }} as answer,
    reference,
    address,
    latitude,
    longitude,
    published_at,
    proposal_notes_count,
    coauthorships_count,
    position,
    participatory_text_level,
    created_in_meeting,
    collaborative_draft_origin,
    cost,
    cost_report,
    execution_period,
    state_published_at,
    endorsements_count,
    {{ lang('title') }} as title,
    {{ lang('body') }} as body,
    comments_count,
    follows_count
from {{ source('decidim', 'decidim_proposals_proposals') }}
